# Generated by Django 2.2.7 on 2019-11-19 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmt_act', '0002_auto_20191119_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings_workshops',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
