# Generated by Django 2.2.7 on 2019-11-19 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmt_act', '0003_auto_20191119_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll_tw',
            unique_together={('user_id', 'tw_id', 'enrolled')},
        ),
    ]
