# Generated by Django 2.2.7 on 2019-11-19 21:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmt_act', '0004_auto_20191120_0245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll_tw',
            unique_together={('user_id', 'tw_id')},
        ),
    ]
