# Generated by Django 2.2.7 on 2019-11-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmt_act', '0005_auto_20191120_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings_workshops',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
