# Generated by Django 2.2.7 on 2019-11-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmt_act', '0006_trainings_workshops_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll_tw',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
